steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', '-b', 'develop','https://github.com/ne250040/data-fusion-1.git']
#  - name: gcr.io/cloud-builders/gcloud
#    entrypoint: 'bash'
#    args: ['-c', 'gcloud secrets versions access latest --secret=cdfbuild-sa-keyfile > cdfbuild-sa-keyfile.json']



